### ISSUE TITLE
setFollow not capturing tweets regularly

### ISSUE THREAD

**Issue by creativelifeform** [fennb/phirehose#76]
I've built an app that will capture tweets that are sent as replies to a specific account. 

I've noticed that this is pretty spotty at best. There are times where it captures things perfectly, then there are others where `enqueueStatus()` just doesn't seem to get called or passed any data. 

Has anyone else experienced this? The very first thing I do inside my method is this

```
if(is_array($data) && $data['in_reply_to_status_id'] !== null && isset($data['id_str'])) {
Logger::output($data['user']['screen_name'] . ': ' . urldecode($data['text']));
}
```
Where `Logger::output()` is just a method that prints out the string. There are times when this simply doesn't happen even though a reply has been sent. Does this mean Phirehose is failing to get the tweet, or is the Streaming API simply not capturing it for some reason (spam filter perhaps)?

Anyone else experience this?

**Comment by fennb** [comment]
Hey there,

The phirehose user group (https://groups.google.com/forum/#!forum/phirehose-users) is probably a better place to ask this question (you'll get a much bigger range of experience) but I'll jot down a few thoughts here all the same.

First up, I'd try changing your filtering code to be a bit broader and look for any tweet with `@username` at the start. The reason is that not all clients include the `in_reply_to_status_id`, in fact, if you just type the reply, this is set to null by default.

Secondly, it matters what connection method you're using - if you're using the sample method, you're only getting a very small amount of the twitter stream (<1% I believe).

To accurately get a users replies, you're either going to have to use the [follow](https://dev.twitter.com/streaming/reference/post/statuses/filter) parameter of the filter method or [UserStreams](https://github.com/fennb/phirehose/blob/master/example/userstream-simple.php).

If you're still having any problems, I recommend submitting your update to the user group!

**Comment by creativelifeform** [comment]
Hi @fennb no this answered things perfectly! I'm currently using the follow parameter using `METHOD_FILTER` but your note about `in_reply_to_status_id` seems to be a possible cause for the issue! I'll check it out now. It's kind of silly that that field is null ever. It shouldn't be imo. Anyway let me see.

**Comment by fennb** [comment]
Hey there!

Replies to tweets should work providing the `@username` is at the start of the tweet. Also, if you're not already using [setFollow()](https://github.com/fennb/phirehose/blob/master/lib/Phirehose.php#L193) may suit your use-case really well, as it explicitly returns tweets by and in-reply-to a specific set of users (you'll still need to do some post-filtering, but it might be easier).

Cheers!

**Comment by creativelifeform** [comment]
Yep I am using `setFollow()` already, actually I just thought of something, here are the things that the `follow` parameter tracks

*Tweets created by the user.
*Tweets which are retweeted by the user.
*Replies to any Tweet created by the user.
*Retweets of any Tweet created by the user.
*Manual replies, created without pressing a reply button (e.g. “@twitterapi I agree”).

So, all I have to do is check if the tweet passed to `enqueueStatus()` has the same user ID as the app. If it does, do nothing (because I don't want to record the app's tweets) and if it doesn't, then it must be a reply, retweet or manual reply right? So that should probably sort.

**Comment by fennb** [comment]
Yeah, actually that sounds like a pretty neat solution :)

**Comment by creativelifeform** [comment]
;) thanks for your help! Fingers crossed it works (seems to be doing well so far)

**Comment by creativelifeform** [comment]
Okay it worked, but I'm still missing some tweets. I'll head over to the google group and see what they have to say, thanks for all your help @fennb!

**Comment by creativelifeform** [comment]
Hey sorry to keep replying to this thread, not getting any traction over at the Google group, I'm wondering about the consume method, would there be some way to delay this so that every attempt to consume is staggered? Perhaps that would improve consumption rates as it would have more time in between checks? I'm thinking maybe `sleep()` inside of it somewhere. I tried using this function inside of my response method (which uses the REST api) so that there is always going to be some buffer between sending back tweets but I was wondering about the actual connection to the streaming API as well.

**Comment by fennb** [comment]
I'm not precisely where you mean in terms of putting a `sleep()` there but as a general rule, you want to have *zero* delays within your `enqueueStatus()` (or anywhere in that code path).

I'll fire some other thoughts off in the google group.

**Comment by creativelifeform** [comment]
Hmm right okay I'll avoid that then. Thanks very much, yeah I'll keep an eye on the group!
